/*
package com.cartoon.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.cartoon.bean.CartoonDown;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
*/
/**
 * DAO for table "CARTOON_DOWN".
*//*

public class CartoonDownDao extends AbstractDao<CartoonDown, String> {

    public static final String TABLENAME = "CARTOON_DOWN";

    */
/**
     * Properties of entity CartoonDown.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    *//*

    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Cover_pic = new Property(2, String.class, "cover_pic", false, "COVER_PIC");
        public final static Property Collect = new Property(3, String.class, "collect", false, "COLLECT");
        public final static Property Catalog = new Property(4, String.class, "catalog", false, "CATALOG");
    };

    private DaoSession daoSession;


    public CartoonDownDao(DaoConfig config) {
        super(config);
    }
    
    public CartoonDownDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    */
/** Creates the underlying database table. *//*

    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CARTOON_DOWN\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"COVER_PIC\" TEXT," + // 2: cover_pic
                "\"COLLECT\" TEXT," + // 3: collect
                "\"CATALOG\" TEXT);"); // 4: catalog
    }

    */
/** Drops the underlying database table. *//*

    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CARTOON_DOWN\"";
        db.execSQL(sql);
    }

    */
/** @inheritdoc *//*

    @Override
    protected void bindValues(SQLiteStatement stmt, CartoonDown entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String cover_pic = entity.getCover_pic();
        if (cover_pic != null) {
            stmt.bindString(3, cover_pic);
        }
 
        String collect = entity.getCollect();
        if (collect != null) {
            stmt.bindString(4, collect);
        }
 
        String catalog = entity.getCatalog();
        if (catalog != null) {
            stmt.bindString(5, catalog);
        }
    }

    @Override
    protected void attachEntity(CartoonDown entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    */
/** @inheritdoc *//*

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    */
/** @inheritdoc *//*

    @Override
    public CartoonDown readEntity(Cursor cursor, int offset) {
        CartoonDown entity = new CartoonDown( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // cover_pic
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // collect
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // catalog
        );
        return entity;
    }
     
    */
/** @inheritdoc *//*

    @Override
    public void readEntity(Cursor cursor, CartoonDown entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCover_pic(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCollect(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCatalog(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    */
/** @inheritdoc *//*

    @Override
    protected String updateKeyAfterInsert(CartoonDown entity, long rowId) {
        return entity.getId();
    }
    
    */
/** @inheritdoc *//*

    @Override
    public String getKey(CartoonDown entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    */
/** @inheritdoc *//*

    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
*/
