/*
package com.cartoon.greendao;

import android.database.sqlite.SQLiteDatabase;

import com.cartoon.bean.CartoonDown;
import com.cartoon.bean.CartoonItem;
import com.cartoon.bean.Listener;
import com.cartoon.bean.BangaiDownLoadList;
import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

*/
/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 *//*

public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cartoonDownDaoConfig;
    private final DaoConfig cartoonItemDaoConfig;
    private final DaoConfig listenerDaoConfig;
    private final DaoConfig bangaiDownDaoConfig;

    private final   CartoonDownDao cartoonDownDao;
    private final   CartoonItemDao cartoonItemDao;
    private final BangaiDownDao  bangaiDownDao;
    private final   ListenerDao    listenerDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cartoonDownDaoConfig = daoConfigMap.get(CartoonDownDao.class).clone();
        cartoonDownDaoConfig.initIdentityScope(type);

        bangaiDownDaoConfig = daoConfigMap.get(BangaiDownDao.class).clone();
        bangaiDownDaoConfig.initIdentityScope(type);

        cartoonItemDaoConfig = daoConfigMap.get(CartoonItemDao.class).clone();
        cartoonItemDaoConfig.initIdentityScope(type);

        listenerDaoConfig = daoConfigMap.get(ListenerDao.class).clone();
        listenerDaoConfig.initIdentityScope(type);

        cartoonDownDao = new CartoonDownDao(cartoonDownDaoConfig, this);
        bangaiDownDao = new BangaiDownDao(bangaiDownDaoConfig, this);
        cartoonItemDao = new CartoonItemDao(cartoonItemDaoConfig, this);
        listenerDao = new ListenerDao(listenerDaoConfig, this);

        registerDao(CartoonDown.class, cartoonDownDao);
        registerDao(BangaiDownLoadList.class,bangaiDownDao);
        registerDao(CartoonItem.class, cartoonItemDao);
        registerDao(Listener.class, listenerDao);
    }
    
    public void clear() {
        cartoonDownDaoConfig.getIdentityScope().clear();
        bangaiDownDaoConfig.getIdentityScope().clear();
        cartoonItemDaoConfig.getIdentityScope().clear();
        listenerDaoConfig.getIdentityScope().clear();
    }

    public CartoonDownDao getCartoonDownDao() {
        return cartoonDownDao;
    }

    public CartoonItemDao getCartoonItemDao() {
        return cartoonItemDao;
    }

    public ListenerDao getListenerDao() {
        return listenerDao;
    }

    public BangaiDownDao getBangaiDownDao() {
        return bangaiDownDao;
    }

}
*/
